name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.12-slim

    steps:
    - name: Install dependencies
      run: apt-get update && apt-get install -y curl git libimage-exiftool-perl gcc libffi-dev g++

    - name: Checkout
      uses: actions/checkout@v4

    - name: install uv
      run: pip install uv

    - name: Install dependencies
      run: |
        uv pip install --system -r requirements.txt

    - name: Run tests
      run: |
        mv config_files/iz_config.unittest.py config_files/iz_config.py
        mv settings_template.py settings.py
        mv server_host_settings.template.py server_host_settings.py
        cd tests
        pytest iz_importer_tests --junitxml=report.xml

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          test-results/
          *.xml 