name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.12-slim

    steps:
    - name: Checkout and update submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install dependencies
      run: apt-get update && apt-get install -y curl git libimage-exiftool-perl

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: 
      run: |
        cd metadata_tools
        git checkout sy-encoding

    - name: Install dependencies
      run: |
        uv pip install --system -r requirements.txt
        uv pip install --system -r metadata_tools/requirements.txt

    - name: Run tests
      run: |
        mv config_files/iz_config.unittest.py config_files/iz_config.py
        mv settings_template.py settings.py
        mv server_host_settings.template.py server_host_settings.py
        cd tests
        pytest iz_importer_tests

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          test-results/
          *.xml 